### ISSUE TITLE
SDK bug

### ISSUE THREAD

**Issue by Kaiser-Wu** [jpush/jiguang-sdk-java#1]
https://report.jpush.cn/v3/received/detail
送达统计详情 的接口 在 SDK5.0.5 版本中 对应的响应实体类 ReceivedDetailGetResult 成员属性的 json 映射字段是错误的。
Unrecognized field "live_acivity_send" 
对应的成员变量：
@JsonProperty("live_acivity_sent")
private Long liveAcivitySent;

导致相应数据反序列化失败，抛出异常

**Comment by wicked-tc130** [comment]
感谢指出，在5.0.6修正了。
