### ISSUE TITLE
新版本的短信推送API移到那里去了

### ISSUE THREAD

**Issue by githubhxd1995** [jpush/jiguang-sdk-java#2]
在旧版本中我是用如下的代码发送短信
`        SMSPayload payload = SMSPayload.newBuilder()
                .setMobileNumber(mobilePhone)
                .setTempId(1)
                .addTempPara("code", code)
                .build();`
但是新版本找不到直接使用手机号发短信的地方，在官网也看不到介绍，想了解这个API现在移到那里去了

**Comment by wicked-tc130** [comment]
官网文档：https://docs.jiguang.cn/jpush/server/push/rest_api_v3_push#sms_message%EF%BC%9A%E7%9F%AD%E4%BF%A1

SDK在5.0.7的版本中补充了SmsMessage，欢迎使用。

**Comment by githubhxd1995** [comment]
好的，感谢🙏
