### ISSUE TITLE
没测试就上线了？请求400

### ISSUE THREAD

**Issue by 1729051657** [jpush/jiguang-sdk-java#4]
<img width="1018" alt="image" src="https://github.com/user-attachments/assets/772fddbd-4900-4e9f-a633-6b054ff3312d">

**Comment by wicked-tc130** [comment]
不好意思，给你带来了不好的体验，能否提供下复现代码和使用版本？

**Comment by wicked-tc130** [comment]
相同类型问题：https://github.com/jpush/jiguang-sdk-java/issues/5

此问题已处理
